name: ChioscoApp

options:
  bundleIdPrefix: it.rfi
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: it

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  ChioscoApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - ChioscoApp

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: it.rfi.ChioscoApp
        INFOPLIST_FILE: ChioscoApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: "" # Lascia vuoto o inserisci il tuo Team ID
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone e iPad
        SUPPORTS_MACCATALYST: false
        SWIFT_VERSION: "5.9"
        ENABLE_PREVIEWS: true

    info:
      path: ChioscoApp/Info.plist
      properties:
        CFBundleDisplayName: "Chiosco Ingresso"
        CFBundleDevelopmentRegion: it_IT
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

schemes:
  ChioscoApp:
    build:
      targets:
        ChioscoApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
